# Generated by Django 5.1.1 on 2024-09-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='_signal_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
